Language = {};
Help = {};
Modules = [
	{name:"Status",mode:null,display:"1"},
	{name:"Network",mode:null,display:"1"},
	{name:"Secure",mode:null,display:"1"},
  {name:"Application",mode:null,display:"1"},
	{name:"Management",mode:null,display:"1"},
	/*{name:"diagnose",mode:1,display:"1"},*/
	{name:"Help",mode:1,display:"1"}
]; 

Apppanels = {
	"Status":[
		{name:"Sta_Overview",init:"init_status_set",mode:null,display:"1"},
		{name:"Sta_WAN",init:"init_IPlink_set",mode:null,display:"1"},
		{name:"Sta_LAN",init:"init_Wireless_set",mode:null,display:"1"},
		/*{name:"Sta_Voice",mode:null,display:"1"},*/
		{name:"Sta_Management",init:"init_tr069satus_set",mode:null,display:"1"},
		{name:"Sta_telligent",init:"init_Intelligent_set",mode:null,display:"1"}
	],
	"Network":[
		{name:"Net_Network",init:"init_nnwan_set",mode:null,display:"1"},
		{name:"Net_LAN",init:"init_ipv4_set",mode:null,display:"1"},
		{name:"Net_WLAN",init:"init_nwbasic_set",mode:null,display:"1"},
		{name:"Net_Management",init:"init_nmitms_set",mode:null,display:"1"},
		{name:"Net_QoS",init:"init_nqbasic_set",mode:null,display:"1"},
		{name:"Net_NTP",init:"init_nntpntp_set",mode:null,display:"1"},
		{name:"Net_Route",init:"init_route_set",mode:null,display:"1"},
		{name:"Net_UsersLimit",init:"init_userslimit_set",mode:null,display:"1"}
	],
		
	"Secure":[
		{name:"Secu_WAN",init:"init_sew_set",mode:null,display:"1"},
		{name:"Secu_Firewall",init:"init_Firewall_set",mode:null,display:"1"},
		{name:"Secu_MAC",init:"init_sem_set",mode:null,display:"1"},
		{name:"Secu_port",init:"init_SeP_set",mode:null,display:"1"}
	],
	"Application":[
		{name:"App_DDNS",init:"init_ddns_set",mode:null,display:"1"},
		{name:"App_NAT",init:"init_alg_set",mode:null,display:"1"},
		{name:"App_UPnP",init:"init_upnp_set",mode:null,display:"1"},
		/*{name:"App_Voice",mode:null,display:"1"},*/
		{name:"App_IGMP",init:"init_Muticast_set",mode:null,display:"1"},
		{name:"App_Application",init:"init_Dowanload_set",mode:null,display:"1"}
	],
	"Management":[
		{name:"Mng_User",init:"init_MUuser_set",mode:null,display:"1"},
		{name:"Mng_Device",init:"init_MDdevice_set",mode:null,display:"1"},
		{name:"Mng_Log",init:"init_MLcheck_set",mode:null,display:"1"},
		{name:"Mng_upgrade",init:"init_upgrade_set",mode:null,display:"1"},
		{name:"Mng_Maintain",init:"init_Maintain_set",mode:null,display:"1"},
		{name:"MngDia_Diagnose",init:"init_Ping_set",mode:null,display:"1"}
	],
	/*"diagnose":[
	  {name:"Dia_Diagnose",mode:null,display:"1"},
	  {name:"Dia_Busdiagnose",mode:null,display:"1"},
	  {name:"Dia_predictive",mode:null,display:"1"}
	],*/
	"Help":{name:"Help_Help",mode:null,display:"1"}
};

Applications = {
	"Sta_Overview":[
		{name:"SO_Overview",init:"init_status_set",display:"1"},
		{name:"SO_Wizard",init:"init_Wizard_set",display:"1"}
	],
	"Sta_WAN":[
		{name:"SW_IPinfo",init:"init_IPlink_set",display:"1"},
		{name:"SW_Linkinfo",init:"init_link_set",display:"1"}
	],
	"Sta_LAN":[
		{name:"SL_WLANinfo",init:"init_Wireless_set",display:"1"},
		{name:"SL_Ethinfo",init:"init_Ethernetport_set",display:"1"}/*,
		{name:"SL_USBinfo",init:"init_usb_set",display:"1"}*/
	],
	/*"Sta_Voice":{name:"SV_Voiceinfo",init:"init_Voiceinfo_set",display:"1"},*/
	"Sta_Management":[
		{name:"SM_Interactive",init:"init_tr069satus_set",display:"1"},
		{name:"SM_Setupstatus",init:"init_service_setsatus_set",display:"1"}
	],
	"Sta_telligent":[
	{name:"SI_Intelligent",init:"init_Intelligent_set",display:"1"}
	],
	"Net_Network":[
		{name:"NN_WAN",init:"init_nnwan_set",display:"1"},
		{name:"NN_VLAN",init:"init_vlan_set",display:"1"}
	],
	"Net_LAN":[
		{name:"ND_IPv4",init:"init_ipv4_set",display:"1"},
		{name:"ND_IPv6",init:"init_ipv6_set",display:"1"},
		{name:"ND_Named",init:"init_ndnamed_set",display:"1"}
	],
	"Net_WLAN":[
		{name:"NW_Basic",init:"init_nwbasic_set",display:"1"},
		{name:"NW_Advanced",init:"init_nwAdvanced_set",display:"1"}
	],
	"Net_Management":[
		{name:"NM_ITMS",init:"init_nmitms_set",display:"1"},
		{name:"NM_Loid",init:"init_loid_set",display:"1"}
	],
	"Net_QoS":[
		{name:"NQ_Basic",init:"init_nqbasic_set",display:"1"},
		{name:"NQ_Advanced",init:"init_nqadvanced_set",display:"1"},
		{name:"NQ_Categoryset",init:"init_Categoryset_set",display:"1"},
		{name:"NQ_AppBusiness",init:"init_AppBusiness_set",display:"1"},
		{name:"NQ_EntranceSpeed",init:"init_EntranceSpeed_set",display:"1"}
	],
	"Net_NTP":[
		{name:"NNTP_NTP",init:"init_nntpntp_set",display:"1"}
	],
	"Net_Route":[
		{name:"NR_Route",init:"init_route_set",display:"1"}
	],
	"Net_UsersLimit":[
		{name:"NU_UsersLimit",init:"init_userslimit_set",display:"1"}
	],
	"Secu_WAN":[
		{name:"SeW_WAN",init:"init_sew_set",display:"1"}
	],
	"Secu_Firewall":[
		{name:"SeF_Firewall",init:"init_Firewall_set",display:"1"}
	],
	"Secu_MAC":[
		{name:"SeM_MAC",init:"init_sem_set",display:"1"}
	],
	"Secu_port":[
	  {name:"SeP_port",init:"init_SeP_set",display:"1"}
	],
	"App_DDNS":[
		{name:"AD_DDNS",init:"init_ddns_set",display:"1"}
	],
	"App_NAT":[
		{name:"AN_ALG",init:"init_alg_set",display:"1"},
		{name:"AN_DMZ",init:"init_dmz_set",display:"1"},
		{name:"AN_VirtualServer",init:"init_VirtualServer_set",display:"1"}
	],
	"App_UPnP":[
		{name:"AU_UPnP",init:"init_upnp_set",display:"1"}
	],
	/*"App_Voice":[
		{name:"AV_Pchange",init:"init_voice_server",display:"1"},
		{name:"AV_Basic",init:"init_avbasic_set",display:"1"},
		{name:"AV_BasicH248",init:"init_avbasicH248_set",display:"1"},
		{name:"AV_Advanced",init:"init_avadvanced_set",display:"1"},
		{name:"AV_AdvancedH248",init:"init_avadvancedH248_set",display:"1"},
		{name:"AV_Addtional",init:"init_Addtional_set",display:"1"},
		{name:"AV_AddtionalIMS",init:"init_AddtionalIMS_set",display:"1"},
		{name:"AV_AddtionalH248",init:"init_AddtionalH248_set",display:"1"},
		{name:"AV_Digitalmap",init:"init_Digitalmap_set",display:"1"},
		{name:"AV_DigitalmapH248",init:"init_DigitalmapH248_set",display:"1"},
		{name:"AV_Fax",init:"init_Fax_set",display:"1"}
	],*/
	"App_IGMP":[
		{name:"AI_Muticast",init:"init_Muticast_set",display:"1"}
	],
	"App_Application":[
		{name:"AA_Dowanload",init:"init_Dowanload_set",display:"1"}
	],
	"Mng_User":[
		{name:"MU_User",init:"init_MUuser_set",display:"1"},
		{name:"MU_Useradmin",init:"init_MUuseradmin_set",display:"1"}
	],
	"Mng_Device":[
		{name:"MD_Device",init:"init_MDdevice_set",display:"1"}/*,
		{name:"USB_Backup",init:"init_USB_Backup_set",display:"1"}*/
	],
	"Mng_Log":[
		{name:"ML_Check",init:"init_MLcheck_set",display:"1"},
		{name:"ML_Setting",init:"init_MLsetting_set",display:"1"}
	],
	"Mng_upgrade":[
	{name:"MU_upgrade",init:"init_upgrade_set",display:"1"}
	],
	"Mng_Maintain":[
		{name:"MM_Maintain",init:"init_Maintain_set",display:"1"}
	],
	"MngDia_Diagnose":[
		{name:"MDD_Ping",init:"init_Ping_set",display:"1"},
		{name:"MDD_Tracert",init:"init_Tracert_set",display:"1"},
		{name:"MDD_Inform",init:"init_Inform_set",display:"1"}
	],
	/*"Dia_Diagnose":[
		{name:"DD_Ping",init:"init_Ping_set",display:"1"},
		{name:"DD_Tracert",init:"init_Tracert_set",display:"1"},
		{name:"DD_Inform",init:"init_Inform_set",display:"1"}
	],
	"Dia_Busdiagnose":[
	  {name:"DB_diagnose",init:"init_Busdiagnose_set",display:"1"}
	 ],
	 "Dia_predictive":[
	  {name:"DB_predictive",init:"init_predictive_set",display:"1"}
	 ],*/
	"Help_Help":[
		{name:"HH_Help",init:"init_help_set",display:"1"}
	]
};

Panels = {
	"SO_Overview":[
		{type:0,name:"Title_base",mode:"val",tags:[
			{name:"title_base_tip",type:"info_contextone"},
			{name:"device_base_list",type:"simple_tableone"}
		]},
		/*{type:0,name:"Title_pon",mode:"val",tags:[
			{name:"pon_info_list",type:"simple_tableone"}
		]},*/
		{type:0,name:"Title_reg",mode:"val",tags:[
			{name:"reg_info_list",type:"simple_tableone"}
		]}/*,
		{type:0,name:"Title_wan",mode:"val",tags:[
			{name:"wan_info_list",type:"simple_tabletwo",mode:"2",action:"{aaction:'link_func'}"}
		]},
		{type:0,name:"Title_wifi",mode:"val",tags:[
			{name:"wifi_info_list",type:"simple_tableone",action:"wifi_func"}
		]},
		{type:0,name:"Title_lan",mode:"val",tags:[
			{name:"lan_info_list",type:"simple_tabletwo",mode:"2"}
		]}*/
	],
	"SO_Wizard":[
		{type:0,name:"Wizard1_info",mode:"no_val",tags:[
			{name:"Title_wizard1_label",type:"info_contextone"},
			{name:"Wizard_wan_1_label",type:"simple_select"},
			{name:"Means_access",type:"radio_group",key:['bridge','route'],value:['0','1']},
			{name:"Wizard_wan_1_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"Wizard_wan_1_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"Wizard_button1_button",type:"btn_array",mode:"['nextstep']",action:"['wizard1_save']"}
		]},
		{type:0,name:"Wizard2_info",mode:"no_val",tags:[
			{name:"Title_wizard2_label",type:"info_contextone"},
			{name:"Wizard_checkbox02_checkbox",type:"simple_check",value:"[1]"},
			{name:"Wizard_text02_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"Wizard_password02_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"Wizard_button2_button",type:"btn_array",mode:"['Previous','nextstep']",action:"['Previous2_save','nextstep2_save']"}
		]},
		{type:0,name:"Wizard3_info",mode:"no_val",tags:[
			{name:"Title_wizard3_label",type:"info_contextone"},
			{name:"Wizardselect_select",type:"simple_select"},
			{name:"iTV_Label",type:"simple_checkmulti"},
			{name:"SmartTV_label",type:"simple_checkmulti"},
			{name:"Wizard_button3_button",type:"btn_array",mode:"['Previous','nextstep']",action:"['Previous3_save','nextstep3_save']"}
		]},
		{type:0,name:"Wizard4_info",mode:"no_val",tags:[
			{name:"Title_wizard4_label",type:"info_contextone"},
			{name:"Wizard_checkbox04_checkbox",type:"simple_check",value:"[1]"},
			{name:"Wizard_password04_01_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"Wizard_password04_02_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"Wizard_password04_03_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"Wizard_button4_button",type:"btn_array",mode:"['Previous','nextstep']",action:"['Previous4_save','nextstep4_save']"}
		]},
		{type:0,name:"Wizard5_info",mode:"no_val",tags:[
			{name:"Title_wizard5_label",type:"info_contextone"},
			{name:"Wizard_button4_button",type:"btn_array",mode:"['Previous','finish']",action:"['Previous5_save','finish_save']"}
		]}
	],
	"SW_IPinfo":[
		{type:0,name:"Title_wan_satus_label",mode:"val",tags:[				
			{name:"Table_wan_ipv4_table",type:"info_contextone"},
			{name:"ipv4_stat_list",type:"simple_tabletwo",mode:"2"},
			{name:"Traffic_Statistics_ipv4_table",type:"info_contextone"},
			{name:"ipv4_Statistics_list",type:"simple_tabletwo",mode:"2"}
		]},
		{type:0,name:"Table_wan_ipv6_table",mode:"tab",tags:[				
			{name:"ipv6_stat_list",type:"simple_tabletwo",mode:"2"},
			{name:"Traffic_Statistics_ipv6_table",type:"info_contextone"},
			{name:"ipv6_Statistics_list",type:"simple_tabletwo",mode:"2"}
		]}
	],
	"SW_Linkinfo":[
		{type:0,name:"Title_pon_satus_label",mode:"val",tags:[
			{name:"Table_pon1_Networklinks_table",type:"info_contextone"},
			{name:"Table_pon1_Networklinks_list",type:"simple_tableone"},
			{name:"Table_pon1_Networklinks_userlist",type:"simple_tableone"},
			{name:"Table_pon5_performance_table",type:"info_contextone"},
			{name:"Table_pon5_Performance_list",type:"simple_tableone"},
			{name:"Table_pon5_Performance_userlist_hubei",type:"simple_tableone"},
			{name:"Table_pon5_Performance_userlist",type:"simple_tableone"}
		]}
	],
	"SL_WLANinfo":[
	  {type:0,name:"Title_wlan_satus_label",mode:"val",tags:[
			{name:"Title_wlaninfo2_table",type:"info_contextone"},
			{name:"wlaninfo_stat_list",type:"simple_tableone"}
		]},
		{type:0,name:"Table_wlanstat",mode:"val",tags:[
			{name:"wlan_stat_list",type:"simple_tabletwo",mode:"2"}
		]},
		{type:0,name:"Table_wlanssid_table",mode:"val",tags:[
			{name:"wlanssid_stat_list",type:"simple_tabletwo",mode:"2"}
		]}
	],
	"SL_Ethinfo":[
		{type:0,name:"Title_eth_satus_label",mode:"no_val",tags:[
			{name:"Table_landhcp_table",type:"info_contextone"},
			{name:"landhcp_stat_list",type:"simple_tabletwo",mode:"2"}
		]},
		{type:0,name:"Table_laninterface_table",mode:"no_val",tags:[
			{name:"laninterface_stat_list",type:"simple_tabletwo",mode:"2"}
		]}
	],
	/*"SL_USBinfo":[
		{type:0,name:"Title_usb_satus_label",mode:"no_val",tags:[
			{name:"usb_satus_tip",type:"simple_tableone"},
			{name:"UsbShare",type:"simple_context"},
			{name:"UsbPrintShare",type:"simple_context"},
			{name:"PrinterInfo",type:"simple_context"}
		]}
	],*/
	/*"SV_Voiceinfo":[
		{type:0,name:"Title_voice_satus_label",mode:"no_val",tags:[
			{name:"voice_satus_list",type:"simple_tabletwo",mode:"2"}
		]}
	],*/
	"SM_Interactive":[
		{type:0,name:"Title_tr069_satus_label",mode:"no_val",tags:[
			{name:"utr069_satus_list",type:"simple_tableone"}
		]}
	],
	"SM_Setupstatus":[
		{type:0,name:"Title_service_set_satus_label",mode:"no_val",tags:[
			{name:"service_set_satus_list",type:"simple_tableone"}
		]}
	],
	"SI_Intelligent":[
	  {type:0,name:"Intelligent_label",mode:"no_val",tags:[
			{name:"Distribution_link_satus",type:"simple_context"},
			{name:"Distribution_Register_satus",type:"simple_context"},
			{name:"Distribution_Widget_satus",type:"simple_context"}
		 ]}
	],
	"NN_WAN":[
		{type:0,name:"wanconnect",mode:"val",tags:[
			//{name:"wanoption",type:"btn_arrayone",mode:"['mod','delbtn']",action:"['mode_wan_info','del_wan_info']"},
			{name:"wan_link_list",type:"simple_tablefour",mode:"5",action:"{mod:'mode_wan_info',del:'del_wan_info'}"},
			{name:"del_waninfo",type:"info_context"},
			{name:"wanlink_add_button",type:"btn_array",mode:"['addlist']",action:"['add_wan_info']"}
		]},
		{type:0,name:"wan_set_label",mode:"val",tags:[
			{name:"indexid_text",type:"simple_text",display:'0'},
			{name:"indexid1_text",type:"simple_text",display:'0'},
			{name:"indexid2_text",type:"simple_text",display:'0'},
			{name:"WanIP_Mode_select",type:"simple_select",value:['1','2','3'],action:"WanIP_Mode_disabled"},
			{name:"WanAddress_select",type:"simple_select",value:['3','1','2'],action:"wan_disabled_show"},
			{name:"WanAddressv6_select",type:"simple_select",value:['3','IP'],action:"wanv6_disabled_show"},
			{name:"WanAddresstype_select",type:"simple_select",value:['1','2'],action:"wanv4v6_disabled_show"},
			{name:"Wan_linkmode_select",type:"simple_select",value:['1','2'],action:"Wan_linkmode_show"},
			//{name:"PPPExpand_Enable",type:"simple_check",value:"[1]",action:"PPPExpand_disabled"},//ipv6
			{name:"wan_port",type:"simple_checkmulti"},
			{name:"ssid_port",type:"simple_checkmulti"},
			{name:"dhcpserver_Enable",type:"simple_check",value:"[1]"},
			{name:"NAT_Enable",type:"simple_check",value:"[1]"},
			{name:"WanServicemode_select",type:"simple_select",value:['1','2','3','4','5','6','7','8'],action:"WanServicemode_disabled"},
			//{name:"vlanmode_select",type:"simple_select",value:['TAG','UNTAG','TRANSPAREN'],action:"vlanmode_disabled"},
			{name:"vlanenabled_checkbox",type:"simple_check",value:"[1]",action:"vlan_disabled"},
			{name:"WanVlanID_text",type:"simple_text",len:'4',check:"text_num"},
			{name:"MulticastVlan_text",type:"simple_text",len:'4',check:"text_num1"},
			{name:"wan802enabled_checkbox",type:"simple_check",value:"[1]",action:"wan802_disabled"},
			{name:"Wan_802_1_P_select",type:"simple_select",value:['0','1','2','3','4','5','6','7']},
			{name:"DSCP_Enable",type:"simple_check",value:"[1]",action:"DSCP_disabled"},
			{name:"DSCP_text",type:"simple_text",check:"text_num1"},
			{name:"WanMTU_text",type:"simple_text",len:'4',check:"text_num1"},
			{name:"WanUserName_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"WanPassword_text",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"WanIPaddress_text",type:"simple_text",check:"text_ip"},
			{name:"Wanmask_text",type:"simple_text",check:"text_mask"},
			{name:"pppoeProxy_Enable",type:"simple_check",value:"[1]"},
			{name:"AuthenticationType_select",type:"simple_select",value:['0','1','2']},
			{name:"Dialingmode_select",type:"simple_select",value:['2','3']},
			{name:"Timeout_text",type:"simple_text",check:"text_num1"},
			{name:"DefaultGateway_text",type:"simple_text",check:"text_ip1"},
			{name:"DNS1_text",type:"simple_text",check:"text_ip1"},
			{name:"DNS2_text",type:"simple_text",check:"text_ip1"},
			{name:"DNS3_text",type:"simple_text",check:"text_ip1"},
			//ipv6
			{name:"Obtain_address_select",type:"simple_select",value:['3','1','2','4'],action:"Obtain_address_disabled"},
			{name:"ipv6addr_text",type:"simple_text",check:"text_ipv6"},
			{name:"Obtain_Gateway_select",type:"simple_select",value:['0','1'],action:"Obtain_Gateway_disabled"},
			{name:"ipv6Gate_text",type:"simple_text",check:"text_ipv6"},
			{name:"Obtain_dns_select",type:"simple_select",value:['0','1','2'],action:"Obtain_dns_disabled"},
			{name:"ManualDNS1_text",type:"simple_text",check:"text_ipv61"},
			{name:"ManualDNS2_text",type:"simple_text",check:"text_ipv61"},
			{name:"ManualDNS3_text",type:"simple_text",check:"text_ipv61"},
			{name:"WanDslite_checkbox",type:"simple_check",value:"[1]",action:"WanDslite_disabled"},
			{name:"SetupMode_select",type:"simple_select",value:['0','1'],action:"SetupMod_disabled"},
			{name:"aftraddr_text",type:"simple_text"},
			{name:"dhcpPrefix_delegation_checkbox",type:"radio_group",key:"['None','static','PD','RA']",value:"['1','2','3','4']",action:"dhcpPrefix_disabled"},
			{name:"ipv6addrPrefix_text",type:"simple_text"},
			{name:"Option60enabled_checkbox",type:"simple_check",value:"[1]",action:"Option60_disabled"},
			{name:"Option60_text",type:"simple_text",len:'12',check:"text_az09"},
			{name:"wanset_button",type:"btn_array",mode:"['savebtn','Cancel']",action:"['add_wanset_save','Cancel_addwanlist']"}
		]}
	],
	"NN_VLAN":[
		{type:0,name:"VLAN_info",mode:"val",tags:[
			{name:"vlan_connect_list",type:"simple_tablefour",mode:"5",value:"['0','1']"},
			{name:"VLAN_tips",type:"info_context"},
			{name:"vlantable_button",type:"btn_array",mode:"['savebtn','Cancel']",action:"['add_vlantable_save','Cancel_vlantable']"}
		]}
	],
	"ND_IPv4":[
		{type:0,name:"ipv4_set",mode:"no_val",tags:[
			{name:"LanIP_Address_text",type:"simple_text",check:"text_ip"},
			{name:"LanSubmask_text",type:"simple_text",check:"text_mask"},
			{name:"ipv4ip_button",type:"btn_array",mode:"['savebtn']",action:"['set_ipv4ip_save']"}
		]},
		{type:0,name:"ipv4title_set",mode:"no_val",tags:[
			{name:"Lan_DHCP_checkbox",type:"simple_check",value:"[1]"},
			{name:"LanStartAddress_text",type:"simple_text",check:"text_ip"},
			{name:"LanEndAddress_text",type:"simple_text",check:"text_ip"},
			{name:"LanDHCP_Submask_text",type:"simple_text",check:"text_mask"},
			//{name:"LanLeaseTime_select",type:"simple_three"},
			{name:"LanAddressRange_checkbox",type:"simple_check",value:"[1]",action:"Address_disable"},
			{name:"lanipv4_tableinfo",type:"info_contextone"},
			{name:"LanLeaseTime_select",type:"simple_select",value:"['60','3600','86400','604800']"},
			{name:"lanipv4_address_list",type:"simple_tablefour",mode:"5"},
			{name:"LanPC_checkbox",type:"simple_check",value:"[1]",action:"PCAddress_disable"},
			//{name:"LanPC_StartAddress_text",type:"simple_text",check:"text_ip"},
			//{name:"LanPC_EndAddress_text",type:"simple_text",check:"text_ip"},
			{name:"LanSTB_checkbox",type:"simple_check",value:"[1]",action:"STBAddress_disable"},
			//{name:"LanSTB_StartAddress_text",type:"simple_text",check:"text_ip"},
			//{name:"LanSTB_EndAddress_text",type:"simple_text",check:"text_ip"},
			{name:"LanPhone_checkbox",type:"simple_check",value:"[1]",action:"PhoneAddress_disable"},
			//{name:"LanPhone_StartAddress_text",type:"simple_text",check:"text_ip"},
			//{name:"LanPhone_EndAddress_text",type:"simple_text",check:"text_ip"},
			{name:"LanCamera_checkbox",type:"simple_check",value:"[1]",action:"CameraAddress_disable"},
			//{name:"LanCamera_StartAddress_text",type:"simple_text",check:"text_ip"},
			//{name:"LanCamera_EndAddress_text",type:"simple_text",check:"text_ip"},
			{name:"Applyipv4_button",type:"btn_array",mode:"['savebtn']",action:"['set_ipv4_save']"}
		]}
	],
	"ND_IPv6":[
		{type:0,name:"ipv6total_set",mode:"no_val",tags:[
			{name:"ManagerAddress_text",type:"simple_text",check:"text_ipv6"},
			{name:"ManagerAddress_button",type:"btn_array",mode:"['savebtn']",action:"['set_ManagerAddress_save']"}
		]},
		{type:0,name:"ipv6_set",mode:"no_val",tags:[
			{name:"LanDNS_select",type:"simple_select",value:"['1','3','2']",action:"LanDNS_disable"},
			{name:"LanDNS_Interface_select",type:"simple_select"},
			{name:"LanPri_DNS_text",type:"simple_text",check:"text_ipv6"},
			{name:"LanSec_DNS_text",type:"simple_text",check:"text_ipv6"},
			//{name:"LanDHCPv6_checkbox",type:"simple_check",value:"[1]"},
			{name:"LanPrefix_select",type:"simple_select",value:"['1','2']",action:"LanPrefix_display"},
			{name:"LanPrefix_text",type:"simple_text"},
			{name:"LanInterface_select",type:"simple_select"},
      {name:"Lanip_radio",type:"radio_group",mode:"4",key:['ipstatus','ipnostatus'],value:['0','1']},    //
      {name:"Landns_radio",type:"radio_group",mode:"4",key:['dnsstatus','dnsnostatus'],value:['0','1']},		//	
			{name:"LanStartAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanEndAddress6_text",type:"simple_text",check:"text_ipv6after"},
			//{name:"circular_route_checkbox",type:"simple_check",value:"[1]"},
			//{name:"LanAddressInfo_checkbox",type:"simple_check",value:"[1]"},
			//{name:"LanOtherInfo_checkbox",type:"simple_check",value:"[1]"},
			//{name:"LanMaxRA_text",type:"simple_text",check:"text_num"},
			//{name:"LanMinRA_text",type:"simple_text",check:"text_num"},
			{name:"LanAddressRange6_checkbox",type:"simple_check",value:"[1]",action:"Address_ipv6disable"},
			{name:"LanPC6_checkbox",type:"simple_check",value:"[1]",action:"PCAddress_ipv6disable"},
			{name:"LanPC_StartAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanPC_EndAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanSTB6_checkbox",type:"simple_check",value:"[1]",action:"STBAddress_ipv6disable"},
			{name:"LanSTB_StartAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanSTB_EndAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanPhone6_checkbox",type:"simple_check",value:"[1]",action:"PhoneAddress_ipv6disable"},
			{name:"LanPhone_StartAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanPhone_EndAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanCamera6_checkbox",type:"simple_check",value:"[1]",action:"CameraAddress_ipv6disable"},
			{name:"LanCamera_StartAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"LanCamera_EndAddress6_text",type:"simple_text",check:"text_ipv6after"},
			{name:"Applyipv6_button",type:"btn_array",mode:"['savebtn']",action:"['set_ipv6_save']"}
		]}
	],
	"ND_Named":[
		{type:0,name:"domain_info",mode:"no_val",tags:[
			{name:"domain_tip",type:"info_contextone"},
			{name:"Domain_text",type:"simple_text",check:"text_string",len:'32'},
			{name:"Apply_button",type:"btn_array",mode:"['savebtn']",action:"['set_Domain_save']"},
			{name:"domain_info_list",type:"simple_tablefour",mode:"5"},
			{name:"domainsave",type:"btn_array",mode:"['devicerename','namesave']",action:"['enable_name_edit','domain_name_save']"}
		]}
	],
	"NW_Basic":[
		{type:0,name:"wlan_set",mode:"val",tags:[
			{name:"nw_Basic_tip",type:"info_contextone"},
			{name:"Bus_Switch_radio",type:"radio_group",key:['open','close'],value:['1','0']},
			{name:"ssid_config_tip",type:"info_contextone"},
			{name:"ssidindex_select",type:"simple_select",value:"['1','2','3','4']",action:"ssidindex_init"},
			{name:"wlanenable",type:"radio_group",key:['open','close'],value:['1','0']},
			{name:"Broadcastssid_checkbox",type:"simple_check",value:"[1]"},
			{name:"Multi_media_checkbox",type:"simple_check",value:"[1]"},
			{name:"wlanssid",type:"text_limitone",check:"text_num"},
			/*{name:"WlanAuthMode_select",type:"simple_select",value:"['0','1','2','3','4','5','6','7','8']",action:"WlanAuthMode_disabled"},*/
			{name:"WlanAuthMode_select",type:"simple_select",value:"['0','1','2','3','4','8']",action:"WlanAuthMode_disabled"},
		  {name:"WlanPwdMode_select",type:"simple_select",value:"['0','1','3','2','4']",action:"Key_disabled"},
		  /*{name:"WlanWepPwd_select",type:"simple_select",value:"['0','1','2']"},*/
		  {name:"WlanKeyBit_select",type:"simple_select",value:"['1','2']"},
		  {name:"CurrKeyindex_select",type:"simple_select",value:"['1','2','3','4']"},
		  {name:"WPSMode_select",type:"simple_select",value:"['1']",action:"WPSMode_select_disable"},
		  {name:"WAPPreShared_text",type:"simple_text",len:'63'},
		  {name:"WPARangrefreshtime_text",type:"simple_text"},
		  {name:"RASIUAserveradd_text",type:"simple_text"},
		  {name:"RASIUSServerport_text",type:"simple_text"},
		  {name:"RADIUSSharekey_text",type:"simple_text"},
		  {name:"KeyOne_text",type:"simple_text"},
		  {name:"KeyTwo_text",type:"simple_text"},
		  {name:"KeyThree_text",type:"simple_text"},
		  {name:"KeyFour_text",type:"simple_text"},
		  {name:"LocalPIN_text",type:"simple_text"},
		  {name:"ClientPIN_text",type:"simple_text"},
		  /*{name:"WlanPassword_password",type:"simple_pwd",check:"text_pass",mode:"5",action:"change_password"},*/
		  {name:"wlan_tips",type:"info_context"},
		  {name:"wlansave",type:"btn_array",mode:"['Certain','Cancel']",action:"['wlan_Certain','wlan_Cancel']"}
		]}
	],
	"NW_Advanced":[
		{type:0,name:"nw_Advanced_info",mode:"no_val",tags:[
			{name:"nw_Advanced_tip",type:"info_contextone"},
			/*{name:"WlanHide_checkbox",type:"simple_check",value:"[1]"},*/
			{name:"WlanChannel_select",type:"simple_select",value:"['0','1','2','3','4','5','6','7','8','9','10','11','12','13']"},
			/*{name:"WlanPlace_select",type:"simple_select",value:"['-12','-11','-10','-9','-8','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7','8','9','10','11','12','13']"},*/
			{name:"WlanPlace_select",type:"simple_select",value:"['0']"},
			{name:"WlanBandWidth_select",type:"simple_select",value:"['0','1','2']"},
			{name:"WlanInterval_select",type:"simple_select",value:"['0','1']"},
			{name:"WlanTransmit_select",type:"simple_select",value:"['5','4','3','2','1']"},
			{name:"RFMode_select",type:"simple_select",value:"['2','3','4','5']"},
      {name:"DTIMPeriod_text",type:"simple_text",check:"text_num"},
		  {name:"BeaconPeriod_text",type:"simple_text",check:"text_num"},
		  {name:"RTSLimit_text",type:"simple_text",check:"text_num"},
		  {name:"FragLimit_text",type:"simple_text",check:"text_num"},
      {name:"NWAdvancedsave",type:"btn_array",mode:"['Certain','Cancel']",action:"['NW_Advanced_Certain','NW_Advanced_Cancel']"}
		]}
	],
	"NM_ITMS":[
		{type:0,name:"itms_info",mode:"no_val",tags:[
			{name:"itms_tip",type:"info_contextone"},
			{name:"Tr69Inform_checkbox",type:"simple_check",value:"[1]"},
			{name:"Informinter_text",type:"simple_text",len:'5',check:"text_num"},
			{name:"Acsurl_text",type:"simple_text",len:'64'},
			{name:"AcsUserName_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"AcsPassWord_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"ConnReqName_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"ConnReqPassWord_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"Middleware_select",type:"simple_select",value:"['1','2','0']",action:"Middleware_display"},
			{name:"MldAddr_text",type:"simple_text"},
			{name:"MldPort_text",type:"simple_text"},
			{name:"Applyitms_button",type:"btn_array",mode:"['savebtn']",action:"['set_itms_save']"}
		]},
		{type:0,name:"Import_info",mode:"no_val",tags:[
			{name:"itmsfile",type:"simple_file",display:"0"},
			{name:"Import_file",type:"simple_text",mode:"1"},
			{name:"Import_set",type:"simple_btn",mode:"save",action:"itmssave_set"}
		]}
	],
	"NM_Loid":[
		{type:0,name:"nm_Loid_info",mode:"no_val",tags:[
			{name:"loid_tip",type:"info_contextone"},
			//{name:"onuSN_text",type:"simple_text"},
			{name:"LoidId_text",type:"simple_text",len:'24',check:"text_string"},
			{name:"Loidpwd_checkbox",type:"simple_check",value:"[1]",action:"loid_password_disable"},
			{name:"Pwd_password",type:"simple_pwd",len:'12',check:"text_pass"},
			//{name:"OLT_Registration_Status",type:"simple_context"},
			//{name:"itms_Certification_Status",type:"simple_context"},
			{name:"Applyloid_button",type:"btn_array",mode:"['savebtn']",action:"['set_loid_save']"}
		]}
	],
	"NQ_Basic":[
		{type:0,name:"advanced_info",mode:"no_val",tags:[
	  	{name:"Template_Index",type:"simple_select",value:"['TR069,VOIP,IPTV,INTERNET','TR069,INTERNET','TR069,VOIP,INTERNET','TR069,IPTV,INTERNET']"},
	  	{name:"QoSEnable_checkbox",type:"simple_check",value:"[1]"},
	  	{name:"Upstream_bandwidth",type:"simple_text"},
			{name:"qoSPlan_select",type:"simple_select",value:"['1','2','3']",action:"disabled_queuelist"},
			{name:"DSCPMarkEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"PMarkType_select",type:"simple_select",value:"['0','2','1']"}
		]},
		{type:0,name:"queue_info",mode:"no_val",tags:[
			{name:"queue_info_list",type:"simple_tablefour",mode:"5"},
			{name:"queue_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_queue_set','cancel_queue_set']"}
		]}
	],
	"NQ_Advanced":[
		{type:0,name:"NQAdvanced_info",mode:"val",tags:[
			{name:"NQAdvancedoption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_NQAdvanced_info','del_NQAdvanced_info']"},
			{name:"NQAdvanced_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_sel',mod:'mod_NQAdvanced'}"}
		]},
		{type:0,name:"Classification_info",mode:"val",tags:[
			{name:"NQdatanum",type:"simple_text",display:"0"},
			{name:"Remark_8021p",type:"simple_text",check:"text_num"},
			{name:"Remark_dscp",type:"simple_text",check:"text_num"},
			{name:"Remark_tc",type:"simple_text",check:"text_num"},
			{name:"queue_select",type:"simple_select",value:"['1','2','3','4','5','6','7','8']"},
			{name:"Classification_button",type:"btn_array",mode:"['savebtn']",action:"['add_Classification_save']"}
		]}
	],
	"NQ_Categoryset":[
	   {type:0,name:"Categoryset_info",mode:"val",tags:[
			{name:"Categorysetoption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_Categoryset_info','del_Categoryset_info']"},
			{name:"Categoryset_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_selqos',mod:'mod_Categoryset'}"}
		]},
		{type:0,name:"datatype_info",mode:"val",tags:[
			{name:"data_stream_number",type:"simple_select"},
			{name:"data_Category_Type",type:"simple_text",display:'0'},
			{name:"data_Protocol",type:"simple_checkmulti"},
			{name:"data_Classification",type:"simple_select",value:"['1','9','3','4','5','6','7','8','12','11','10']"},
			{name:"data_min",type:"simple_text"},
			{name:"data_max",type:"simple_text"},
			{name:"dataClassification_button",type:"btn_array",mode:"['savebtn']",action:"['add_dataClassification_save']"}
		]}
	],
	"NQ_AppBusiness":[
	{type:0,name:"AppBusiness_info",mode:"no_val",tags:[
			{name:"AppBusiness_list",type:"simple_tablefour",mode:"5"},
			{name:"AppBusiness_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_AppBusiness_set','cancel_AppBusiness_set']"}
		]}
	],
	"NQ_EntranceSpeed":[
	{type:0,name:"EntranceSpeed_info",mode:"no_val",tags:[
			{name:"EntranceSpeedup_select",type:"simple_select",value:"['0','1','2','3']",action:"uplimit_display"},
		  //{name:"Speedvalueup_text",type:"simple_text",mode:"6"},
		  {name:"web_aucUpLanLimit",type:"simple_text",mode:"6"},
		  {name:"web_aucUpVlanLimit",type:"simple_text",mode:"6"},
		  {name:"web_aucUpIpLimit",type:"simple_text",mode:"6"},
		  {name:"EntranceSpeeddown_select",type:"simple_select",value:"['0','1','2','3']",action:"downlimit_display"},
		  //{name:"Speedvaluedown_text",type:"simple_text",mode:"6"},
		  {name:"web_aucDownLanLimit",type:"simple_text",mode:"6"},
		  {name:"web_aucDownVlanLimit",type:"simple_text",mode:"6"},
		  {name:"web_aucDownIpLimit",type:"simple_text",mode:"6"},
		  {name:"EntranceSpeed_tips",type:"info_context"},
		  {name:"Entspeed_set",type:"btn_array",mode:"['savebtn']",action:"['EntSpeed_set']"}
		]}
	],
	"NNTP_NTP":[
		{type:0,name:"ntp_info",mode:"no_val",tags:[
			{name:"time_tip",type:"info_contextone"},
			{name:"SystemTime_label",type:"simple_context"},
			{name:"NtpEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"NtpType_select",type:"simple_select",value:"['0','1','2']"},
			{name:"ui_timezone",type:"simple_select",mode:'5',value:"['-12','-11','-10','-9','-8','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6','7','8','9','10','11','12','13']"},
			{name:"NtpInterval_text",type:"simple_text",check:"text_num"},
			{name:"fstserver1",type:"simple_select_text",value:"['clock.fmt.he.net','clock.nyc.he.net','clock.sjc.he.net','clock.via.net','ntp1.tummy.com','time.cachenetworks.com','time.nist.gov','time.windows.com','other']"},
			{name:"fstserver2",type:"simple_select_text",value:"['clock.fmt.he.net','clock.nyc.he.net','clock.sjc.he.net','clock.via.net','ntp1.tummy.com','time.cachenetworks.com','time.nist.gov','time.windows.com','other']"},
			{name:"fstserver3",type:"simple_select_text",value:"['clock.fmt.he.net','clock.nyc.he.net','clock.sjc.he.net','clock.via.net','ntp1.tummy.com','time.cachenetworks.com','time.nist.gov','time.windows.com','other']"},
			{name:"fstserver4",type:"simple_select_text",value:"['clock.fmt.he.net','clock.nyc.he.net','clock.sjc.he.net','clock.via.net','ntp1.tummy.com','time.cachenetworks.com','time.nist.gov','time.windows.com','other']"},
			{name:"fstserver5",type:"simple_select_text",value:"['clock.fmt.he.net','clock.nyc.he.net','clock.sjc.he.net','clock.via.net','ntp1.tummy.com','time.cachenetworks.com','time.nist.gov','time.windows.com','other']"},
			{name:"ntp_set",type:"btn_array",mode:"['savebtn']",action:"['mod_ntp_set']"}
		]}
	],
	"NR_Route":[
		{type:0,name:"staticrouteinfo",mode:"val",tags:[
			{name:"routeoption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_route_info','del_route_info']"},
			{name:"static_route_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_sel',mod:'mod_routeinfo'}"}
		]},
		{type:0,name:"Title_route",mode:"val",tags:[
      {name:"route_index",type:"simple_text",display:'0'},
      {name:"IpVersion_select",type:"simple_select",value:"['1','2']"},
			{name:"route_destaddr_ipmask",type:"simple_text"},
			//{name:"route_ipmask",type:"simple_text",len:'15',check:"text_mask"},
			{name:"route_gateway",type:"simple_text",len:'15',check:"text_ip"},
			{name:"route_interface",type:"simple_select"},
			{name:"routeaddsave",type:"btn_array",mode:"['savebtn']",action:"['add_route_save']"}
		]}
	],
	"NU_UsersLimit":[
		{type:0,name:"UsersLimit_info",mode:"no_val",tags:[
			{name:"UsersLimit_select",type:"simple_select",value:"['0','1']",action:"UsersLimit_disabled"},
			{name:"UsersLimit_text",type:"simple_text",len:'2',check:"text_num"},
			{name:"UsersLimit_button",type:"btn_array",mode:"['savebtn']",action:"['add_UsersLimit_save']"}
		]}
	],
	"SeW_WAN":[
		{type:0,name:"SeW_wan_info",mode:"no_val",tags:[
			{name:"URL_filter_enable_checkbox",type:"simple_check",value:"[1]"},
			{name:"ExcludeMode_select",type:"simple_select",value:['0','1']},
			{name:"ModeurlSave_button",type:"btn_array",mode:"['savebtn']",action:"['ModeSave_save']"}
		]},
		{type:0,name:"SeW_info",mode:"val",tags:[
			{name:"SeWoption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_SewWAN_info','del_SewWAN_info']"},
			{name:"SeW_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_sel',mod:'mod_SewWANinfo'}"}
		]},
		{type:0,name:"URLAddresse_info",mode:"val",tags:[
			{name:"ulindexid_text",type:"simple_text",display:'0'},
			{name:"URLAddress_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"URLSave_button",type:"btn_array",mode:"['savebtn']",action:"['add_URL_save']"}
		]}
	],
	"SeF_Firewall":[
		{type:0,name:"Firewall_info",mode:"no_val",tags:[
			{name:"FirewallEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"Firewalllevel_select",type:"simple_select",value:['0','1','2']},
			{name:"DosEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"Firewall_button",type:"btn_array",mode:"['savebtn']",action:"['add_Firewall_save']"}
		]}
	],
	"SeM_MAC":[
		{type:0,name:"SeM_mac_info",mode:"no_val",tags:[
			{name:"MAC_filter_enable_checkbox",type:"simple_check",value:"[1]"},
			{name:"ExcludeMode_mac_select",type:"simple_select",value:['0','1']},
			{name:"ModemacSave_button",type:"btn_array",mode:"['savebtn']",action:"['ModeMac_save']"}
		]},
		{type:0,name:"SeM_info",mode:"val",tags:[
			{name:"SeMoption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_SemMAC_info','del_SemMAC_info']"},
			{name:"MAC_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_sel',mod:'mod_SemMACinfo'}"}
		]},
		{type:0,name:"MACAddresse_info",mode:"val",tags:[
			{name:"macindexid_text",type:"simple_text",display:'0'},
			{name:"MACAddress_text",type:"simple_text",check:"text_mac"},
			{name:"MACSave_button",type:"btn_array",mode:"['savebtn']",action:"['add_MAC_save']"}
		]}
	],
	"SeP_port":[
	   {type:0,name:"SeP_port_info",mode:"no_val",tags:[
			{name:"port_filter_enable_checkbox",type:"simple_check",value:"[1]"},
			{name:"portMode_select",type:"simple_select",value:['0','1']},
			{name:"ModeportSave_button",type:"btn_array",mode:"['savebtn']",action:"['Modeport_save']"}
		]},
		{type:0,name:"port_tips_label",mode:"val",tags:[
			{name:"SePoption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_SepPort_info','del_SepPort_info']"},
			{name:"port_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_sel',mod:'mod_SepPort'}"}
		]},
		{type:0,name:"portAddresse_info",mode:"val",tags:[
			{name:"portindexid_text",type:"simple_text",display:'0'},
			{name:"port_protocol_select",type:"simple_select",value:"['0','1','2','3','4']",action:"port_protocolsel"},
			{name:"port_lanip_text",type:"text_limittwo"},
			//{name:"port_lanport_select",type:"radio_group",key:"['all1','user1']",value:"[0,1]",action:"port_lanportdisabled"},
			//{name:"port_lanportuser_select",type:"radio_group",key:"['Special1','Scope1']",value:"[0,1]",mode:"4",action:"port_lanportuserdisabled"},
			//{name:"port_lanport_sel",type:"simple_select",value:"['21','23','25','80','53','69','67','68']",mode:"2"},
			{name:"port_Scope_text",type:"text_limittwo"},
			//{name:"port_wanip_radio",type:"radio_group",key:"['all2','user2']",value:"[0,1]",action:"port_wanipdisabled"},
			{name:"port_wanipuser_text",type:"text_limittwo"},
			//{name:"port_wanport_radio",type:"radio_group",key:"['all3','user3']",value:"[0,1]",action:"port_wanportdisabled"},
			//{name:"port_wanportuser_select",type:"radio_group",key:"['Special2','Scope2']",value:"[0,1]",mode:"4",action:"port_wanportuserdisabled"},
			//{name:"port_wanport_sel",type:"simple_select",value:"['21','23','25','80','53','69','67','68']",mode:"2"},
			{name:"port_wanportuser_text",type:"text_limittwo"},
			{name:"portSave_button",type:"btn_array",mode:"['savebtn']",action:"['add_port_save']"}
		]}
	],
	"AD_DDNS":[
		{type:0,name:"ddns_info",mode:"no_val",tags:[
			{name:"DDNSCfgEnabled_Value",type:"simple_check",value:"[1]"},
			{name:"DDNSProvider",type:"simple_context"},
			{name:"ServicePort_text",type:"simple_text",display:'0'},
			{name:"DDNSUsername_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"DDNSPassword_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"DDNSWANInterface_select",type:"simple_select"},
			{name:"DDNSDomainName_text",type:"simple_text",display:'0'},
			{name:"DDNSHostName_text",type:"simple_text",display:'0'},
			{name:"ddns_save",type:"btn_array",mode:"['Certain','Cancel']",action:"['ddns_Submit','ddns_Cancel']"}
		]}
	],
	"AN_ALG":[
		{type:0,name:"alg_info",mode:"no_val",tags:[
			{name:"H323Enable_checkbox",type:"simple_check",value:"[1]"},
			{name:"RTSPEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"L2TPEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"IPSECEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"SIPEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"FTPEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"PPTPEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"SavealgApply_button",type:"btn_array",mode:"['savebtn']",action:"['add_alg_save']"}
		]}
	],
	"AN_DMZ":[
		{type:0,name:"DMZ_info",mode:"no_val",tags:[
			{name:"DMZenable_checkbox",type:"simple_check",value:"[1]",action:"DMZenable_disabled"},
			{name:"DMZwan_select",type:"simple_select"},
			{name:"DMZ_text",type:"simple_text",check:"text_ip"},
			{name:"SavedmzApply_button",type:"btn_array",mode:"['savebtn']",action:"['add_DMZ_save']"}
		]}
	],
	"AN_VirtualServer":[
		{type:0,name:"VirtualServer_label",mode:"no_val",tags:[
			{name:"VirtualServeroption",type:"btn_arrayone",mode:"['addbtn','delbtn']",action:"['add_VirtualServer_info','del_VirtualServer_info']"},
			{name:"static_VirtualServer_list",type:"simple_tablethree",mode:"5",action:"{choose:'check_sel',mod:'mod_VirtualServerinfo'}"}
		]},
		{type:0,name:"Title_VirtualServer",mode:"val",tags:[
			{name:"VirtualServer_indexid",type:"simple_text",display:'0'},
			{name:"VirtualServer_indexid0",type:"simple_text",display:'0'},
			{name:"WANselect_select",type:"simple_select"},
			{name:"ExternalPort_text",type:"simple_text",check:'text_port0'},
			{name:"PortMappingProtocol_select",type:"simple_select",value:['1','2','53','21','4500','110','25','1723','22','23','69','80'],action:"VirtualServer_select_protocol"},
			{name:"InternalClient_text",type:"simple_text",check:"text_ip"},
			{name:"InternalPort_text",type:"simple_text",check:'text_port0'},
			{name:"SaveVirtualServer_button",type:"btn_array",mode:"['savebtn']",action:"['add_VirtualServer_save']"}
		]}
	],
	"AU_UPnP":[
		{type:0,name:"UPnP_label",mode:"no_val",tags:[
			{name:"UPnPEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"Btn_Submit_button",type:"btn_array",mode:"['savebtn']",action:"['add_upnp_save']"}
		]}
	],
	/*"AV_Pchange":[
		{type:0,name:"avpchange_info",mode:"no_val",tags:[
			{name:"ServerType_select",type:"radio_group",mode:"4",key:"['ims','sip','h248']",value:"['0','1','2']"},
			{name:"save_servertype",type:"btn_array",mode:"['savebtn']",action:"['server_change']"}
		]}
	],
	"AV_Basic":[
		{type:0,name:"sipserver_info",mode:"no_val",tags:[
			{name:"ProxyServer_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"ProxyServerPort_text",type:"simple_text",check:"text_port0"},
			{name:"RegistrarServer_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"RegistrarServerPort_text",type:"simple_text",check:"text_port0"},
			{name:"OutboundProxy_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"OutboundProxyPort_text",type:"simple_text",check:"text_port0"},
			{name:"StandbyProxyServer_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"StandbyProxyServerPort_text",type:"simple_text",check:"text_port0"},
			{name:"StandbyRegistrarServer_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"StandbyRegistrarServerPort_text",type:"simple_text",check:"text_port0"},
			{name:"StandbyOutboundProxy_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"StandbyOutboundProxyPort_text",type:"simple_text",check:"text_port0"},
			{name:"sipserver_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_sipserverinfo_set','cancel_sipserverinfo_set']"}
		]},
		{type:0,name:"sipuser_info",mode:"no_val",tags:[
			{name:"sipuser_info_list",type:"simple_tablefour",mode:"5"},
			{name:"sipuser_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_sipuserinfo_set','cancel_sipuserinfo_set']"}
		]}
	],
	"AV_BasicH248":[
	  {type:0,name:"h248server_info",mode:"no_val",tags:[
			{name:"MediaGatewayPort_text",type:"simple_text",check:"text_port0"},
			{name:"MediaGatewayControler_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"MediaGatewayControlerPort_text",type:"simple_text",check:"text_port0"},
			{name:"StandbyMediaGatewayControler_text",type:"simple_text",check:"text_ipDomainvoip"},
			{name:"StandbyMediaGatewayControlerPort_text",type:"simple_text",check:"text_port0"},
			{name:"DeviceIDType_select",type:"simple_select",value:['0','1','2']},
			{name:"DeviceID_text",type:"simple_text"},
			{name:"MessageEncodingType_select",type:"simple_select",value:['0','1']},
			{name:"Physicalset_select",type:"simple_select",value:['0','1'],action:"Physicalset_display"},
			{name:"PhysicalTermIDPrefix_text",type:"simple_text"},
			{name:"PhysicalTermIDStart_text",type:"simple_text"},
			{name:"PhysicalTermIDAddLen_text",type:"simple_text"},
			{name:"RTPPrefix_text",type:"simple_text"},
			{name:"EphemeralTermIDStart_text",type:"simple_text"},
			{name:"EphemeralTermIDAddLen_text",type:"simple_text"},
			{name:"h248server_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_h248serverinfo_set','cancel_h248serverinfo_set']"}
		]},
		{type:0,name:"h248user_info",mode:"no_val",tags:[
			{name:"h248user_tip",type:"info_contextone"},
			{name:"h248user_info_list",type:"simple_tablefour",mode:"5"},
			{name:"h248user_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_h248userinfo_set','cancel_h248userinfo_set']"}
		]}
	],
	"AV_Advanced":[
	  {type:0,name:"avadvanced_label",mode:"no_val",tags:[
			{name:"URIType_select",type:"simple_select",value:['0','1']},
			{name:"DTMFMethod_select",type:"simple_select",value:['0','1','2']},
			{name:"SipLocalPort_text",type:"simple_text",check:"text_port0"},
			{name:"SipDSCPMark_text",type:"simple_text",check:"text_num"},
			{name:"RtpDSCPMark_text",type:"simple_text",check:"text_num"},
			{name:"RegisterExpires_text",type:"simple_text",check:"text_num"},
			{name:"RegisterRetryInterval_text",type:"simple_text",check:"text_num"},
			{name:"SessionExpires_text",type:"simple_text",check:"text_num"},
			{name:"RtpPortStart_text",type:"simple_text",check:"text_port0"},
			{name:"RtpPortEnd_text",type:"simple_text",check:"text_port0"},
			{name:"PRACKEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"BootDeRegisterEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"FlashMin_text",type:"simple_text",check:"text_num"},
			{name:"FlashMax_text",type:"simple_text",check:"text_num"},
			{name:"VadCngEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"RingVoltage_text",type:"simple_text",check:"text_num",display:'0'}
		]},
		{type:0,name:"avadvanced_info",mode:"no_val",tags:[
			{name:"sipuser_advanced_list",value:"['-14','-13','-12','-11','-10','-9','-8','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6']",type:"simple_tablefour",mode:"5"},
			{name:"sipuser_advanced_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_sipuseradvanced_set','cancel_sipuseradvanced_set']"}
		]},
		{type:0,name:"avadvanced_code",mode:"no_val",tags:[
			{name:"sipuser_encode_list",type:"simple_tablefour",mode:"5"},
			{name:"sipencode_advanced_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_sipencode_set','cancel_sipencode_set']"}
		]}
	],
	"AV_AdvancedH248":[
	 {type:0,name:"advancedH248_label",mode:"no_val",tags:[
			{name:"DTMFMethod_h248_select",type:"simple_select",value:['0','1','2']},
			{name:"RtpPortStart_h248_text",type:"simple_text",check:"text_port0"},
			{name:"RtpPortEnd_h248_text",type:"simple_text",check:"text_port0"},
			{name:"FlashMin_h248_text",type:"simple_text",check:"text_num"},
			{name:"FlashMax_h248_text",type:"simple_text",check:"text_num"},
			{name:"VadCngEnable_h248_checkbox",type:"simple_check",value:"[1]"},
			{name:"RingVoltage_h248_text",type:"simple_text",check:"text_num",display:'0'}
		]},
		{type:0,name:"advancedH248_info",mode:"no_val",tags:[
			{name:"h248user_advanced_list",value:"['-14','-13','-12','-11','-10','-9','-8','-7','-6','-5','-4','-3','-2','-1','0','1','2','3','4','5','6']",type:"simple_tablefour",mode:"5"},
			{name:"h248user_advanced_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_h248useradvanced_set','cancel_h248useradvanced_set']"}
		]},
		{type:0,name:"avadvancedh248_code",mode:"no_val",tags:[
			{name:"h248user_encode_list",type:"simple_tablefour",mode:"5"},
			{name:"h248encode_advanced_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_h248encode_set','cancel_h248encode_set']"}
		]}
	],
	"AV_Addtional":[
		{type:0,name:"sipAddtional_info",mode:"no_val",tags:[
			{name:"sipTimeSyncMode_select",type:"simple_select",value:['0','1','2']},
			//{name:"sipCaller_ID_switch",type:"simple_check",value:"[1]"},
			{name:"sipCallIDShowMode_select",type:"simple_select",value:['0','1','2']}
		]},
		{type:0,name:"sipLine_configuration",mode:"no_val",tags:[
			{name:"sipLine_configuration_list",type:"simple_tablefour",mode:"5"},
			{name:"sipLine_configuration_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_sipAddtional_set','cancel_sipAddtional_set']"}
		]}
	],
	"AV_AddtionalIMS":[
	{type:0,name:"imsAddtional_info",mode:"no_val",tags:[
			{name:"TimeSyncMode_select",type:"simple_select",value:['0','1','2']},
			//{name:"Caller_ID_switch",type:"simple_check",value:"[1]"},
			{name:"CallIDShowMode_select",type:"simple_select",value:['0','1','2']},
			{name:"Service_subscription",type:"simple_check",value:"[1]"}
		]},
		{type:0,name:"imsLine_configuration",mode:"no_val",tags:[
			{name:"imsLine_configuration_list",type:"simple_tablefour",mode:"5"},
			{name:"imsLine_configuration_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_imsAddtional_set','cancel_imsAddtional_set']"}
		]}
	],
	"AV_AddtionalH248":[
	{type:0,name:"AddtionalH248_info",mode:"no_val",tags:[
			{name:"HeartbeatMode_select",type:"simple_select",value:['0','1']},
			{name:"HeartbeatCycle_text",type:"simple_text",check:"text_num"},
			{name:"HeartbeatCount_text",type:"simple_text",check:"text_num"},
			//{name:"Caller_switch",type:"simple_check",value:"[1]"},
			{name:"CallIDShowModeh248_select",type:"simple_select",value:['0','1','2']},
			{name:"AddtionalH248_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_AddtionalH248_set','cancel_AddtionalH248_set']"}
		]}
  ],
	"AV_Digitalmap":[
		{type:0,name:"Digitalmap_info",mode:"no_val",tags:[
			{name:"DigitMapEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"DigitMap_textarea",type:"simple_textarea",rows:'6'},
			{name:"DigitMapMode_select",type:"simple_select",value:['1','2']},
			{name:"TWaitTime_select",type:"simple_select",value:['1','2']},
			{name:"DotWaitTime_select",type:"simple_select",value:['0','1','2']},
			{name:"OutNumberContainImmediateDialKey_select",type:"simple_select",value:['1','0']},
			{name:"StartDialingTimer_text",type:"simple_text",check:"text_num"},
			{name:"LongTimerValue_text",type:"simple_text",check:"text_num"},
			{name:"ShortTimerValue_text",type:"simple_text",check:"text_num"},
			{name:"Digitalmap_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_Digitalmap_set','cancel_Digitalmap_set']"}
		]}
	],
	"AV_DigitalmapH248":[
	  {type:0,name:"DigitalmapH248_info",mode:"no_val",tags:[
			{name:"StartDigitTimer_text",type:"simple_text",check:"text_num"},
			{name:"LongTimerValueH248_text",type:"simple_text",check:"text_num"},
			{name:"ShortTimerValueH248_text",type:"simple_text",check:"text_num"},
			{name:"remindersTimerValue_text",type:"simple_text",check:"text_num"},
			{name:"busyTimerValue_text",type:"simple_text",check:"text_num"},
			{name:"callTimerValue_text",type:"simple_text",check:"text_num"},
			{name:"DigitalmapH248_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_DigitalmapH248_set','cancel_DigitalmapH248_set']"}
		]}
	],
	"AV_Fax":[
		{type:0,name:"Fax_info",mode:"no_val",tags:[
			{name:"FaxMode_select",type:"simple_select",value:['1','0']},
			{name:"T30NegotiateMode_select",type:"simple_select",value:['0','1']},
			{name:"Fax_set",type:"btn_array",mode:"['savebtn','cancelbtn']",action:"['save_Fax_set','cancel_Fax_set']"}
		]}
	],*/
	"AI_Muticast":[
		{type:0,name:"Muticast_info",mode:"no_val",tags:[
			{name:"IGMP_label",type:"simple_label"},
			{name:"IGMPSnooping_checkbox",type:"simple_check",value:"[1]"},
			{name:"IGMPProxy_checkbox",type:"simple_check",value:"[1]",action:"Interfacedisabled"},
			{name:"MLD_label",type:"simple_label"},
			{name:"MLDSnooping_checkbox",type:"simple_check",value:"[1]"},
			{name:"MLDProxy_checkbox",type:"simple_check",value:"[1]"},
			{name:"MulticastVLAN_label",type:"simple_label"},
			{name:"InterfaceSelect_select",type:"simple_select",action:"vlandisplay"},
			{name:"MulticastSettings_text",type:"simple_text",check:"text_num"},
			{name:"Muticast_Save_button",type:"btn_array",mode:"['savebtn']",action:"['add_Muticast_save']"}
		]}
	],
	"AA_Dowanload":[
		{type:0,name:"Dowanload_info",mode:"no_val",tags:[
			{name:"DownloadTransports_Value_select",type:"simple_select",value:['0','1']},
			{name:"ServerUrl_text",type:"simple_text",check:"text_ipDomain"},
			{name:"ServerPort_text",type:"simple_text"},
			{name:"HiddenName_checkbox",type:"simple_check",value:"[1]",action:"userdisabled"},
			{name:"DowanloadUserName_text",type:"simple_text",len:'32',check:"text_string"},
			{name:"UserPass_password",type:"simple_pwd",len:'32',check:"text_pass"},
			{name:"usbEquipment_select",type:"simple_select"},
			{name:"DownloadFilePath_text",type:"simple_text"},
			{name:"SaveAsPath_text",type:"simple_text"},
			{name:"DownloadState_text",type:"simple_context"},
			{name:"Dowanload_button",type:"btn_array",mode:"['Begindownload','Refreshdownload','Canceldownload']",action:"['Begin_download','Refresh_download','Cancel_download']"}
		]},
		{type:0,name:"Table_download_tab",mode:"val",tags:[
			{name:"app_download_list",type:"simple_tabletwo",mode:"2"}
		]}
	],
	"MU_User":[
		{type:0,name:"MUuser_info",mode:"no_val",tags:[
			{name:"Username_text",type:"simple_context"},
			{name:"PwdNew_password",type:"simple_pwd",len:'16',check:"text_pass"},
			{name:"PwdCfm_password",type:"simple_pwd",len:'16',check:"text_pass"},
			{name:"MUuser_Save_button",type:"btn_array",mode:"['savebtn']",action:"['add_MUuser_save']"}
		]}
	],
	"MU_Useradmin":[
	  {type:0,name:"MUuseradmin_info",mode:"no_val",tags:[
			{name:"Usernameadmin_text",type:"simple_context"},
			{name:"Pwdold_password",type:"simple_pwd",len:'16',check:"text_pass"},
			{name:"Pwdnewn_password",type:"simple_pwd",len:'16',check:"text_pass"},
			{name:"MUuseradmin_Save_button",type:"btn_array",mode:"['savebtn']",action:"['add_MUuseradmin_save']"}
		]}
	],
	"MD_Device":[
		{type:0,name:"MDdevice_info",mode:"no_val",tags:[
			{name:"Title_factoryset_backup_label",type:"info_contextone"},
			{name:"Title_factoryset_backup_tips_label",type:"info_contextone"},
			{name:"factoryset_button",type:"btn_array",mode:"['factoryset']",action:"['factoryset_save']"},
			{name:"Title_reboot_label",type:"info_contextone"},
			{name:"Title_reboot_tips_label",type:"info_contextone"},
			{name:"reboot_button",type:"btn_array",mode:"['reboot']",action:"['reboot_save']"},
			{name:"factoryset_all_label",type:"info_contextone"},
			{name:"factoryset_all_tips_label",type:"info_contextone"},
			{name:"factoryset_all_button",type:"btn_array",mode:"['factorysetall']",action:"['factorysetall_save']"}
		]}
	],
	/*"USB_Backup":[
	 {type:0,name:"MDUsbdevice_info",mode:"no_val",tags:[
	 		{name:"usbshare_infocontext",type:"info_contextone"},
			{name:"usbshare_checkbox",type:"simple_check",value:"[0]"},
			{name:"usbshare_button",type:"btn_array",mode:"['savebtn']",action:"['usbshare_save']"},
			{name:"MDdevice_infocontext",type:"info_contextone"},
			{name:"RecEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"RecEnable_button",type:"btn_array",mode:"['savebtn']",action:"['RecEnable_save']"},
			{name:"Usbsubarea_infocontext",type:"info_contextone"},
			{name:"Usbsubarea_select",type:"simple_select"},
			{name:"MDdevice_button",type:"btn_array",mode:"['BackupConfiguration']",action:"['MDdevice_save']"}
		]}
	],*/
	"ML_Check":[
		{type:0,name:"MLcheck_info",mode:"no_val",tags:[
			{name:"Title_log_enable_label2",type:"info_contextone"},
			{name:"Title_log_enable_label",type:"simple_contextwhite"},
			{name:"Title_log_level_label2",type:"simple_contextwhite",display:"0"},
			{name:"log_set",type:"btn_array",mode:"['Viewlogbtn','Clearlogbtn']",action:"['refresh_log','Clearlog_set']"}/*,
			{name:"Title_access_log_label1",type:"info_contextone"},
			{name:"Title_access_log_label2",type:"simple_contextwhite"},
			{name:"Title_access_log_label3",type:"simple_contextwhite"},
			{name:"Title_access_log_label4",type:"simple_contextwhite"},
			{name:"Title_access_log_label5",type:"simple_contextwhite"},
			{name:"Title_access_log_label6",type:"simple_contextwhite"},
			{name:"Title_access_log_label7",type:"simple_contextwhite"}*/
		]},
	 {type:0,name:"logtable_info",mode:"val",tags:[
			/*{name:"MLcheck_result_list",type:"simple_tablefive",mode:"2"},*/
			{name:"MLcheck_result_list",type:"info_context"},
			{name:"MLcheck_button",type:"btn_array",mode:"['refresh','close']",action:"['refresh_log','close_log']"}
		]}
	],
	"ML_Setting":[
		{type:0,name:"MLsetting_info",mode:"no_val",tags:[
			{name:"Title_config_log_label",type:"info_contextone"},
			{name:"LogEnable_checkbox",type:"simple_check",value:"[1]"},
			{name:"LevelLog_select",type:"simple_select",value:"['0','1','2','3','4','5','6','7']"},
			{name:"LevelDisplay_select",type:"simple_select",value:"['0','1','2','3','4','5','6','7']"},
			{name:"MLsetting_button",type:"btn_array",mode:"['savebtn']",action:"['MLsetting_save']"}
		]}
	],
	"MU_upgrade":[
	  {type:0,name:"upgrade_info",mode:"no_val",tags:[
			{name:"upgradefile",type:"simple_file",display:"0"},
			{name:"updata_file",type:"simple_text",mode:"1"},
			{name:"update_set",type:"simple_btn",mode:"upgrade",action:"upgrade_set"}
		]},
		{type:0,name:"load_info",mode:"no_val",tags:[
			{name:"load",type:"simple_load"}
		]}
	],
	"MM_Maintain":[
		{type:0,name:"Maintain_info",mode:"no_val",tags:[
			{name:"Title_maintain_end_label",type:"info_contextone"},
			{name:"Maintain_button",type:"btn_array",mode:"['Maintainbtn']",action:"['Maintain_save']"}
		]}
	],
	"MDD_Ping":[
		{type:0,name:"Ping_info",mode:"no_val",tags:[
			{name:"Ping_interface_select",type:"simple_select"},
			{name:"Ping_ip_version_select",type:"simple_select",value:"['ipv4','ipv6']"},
			{name:"Ping_host_text",type:"simple_text",check:"text_ipDomain"},
			{name:"Ping_repetition_Number_text",type:"simple_text",check:"text_num",mode:"4",action:"ping_start"},
			{name:"Ping_result_label",type:"info_contextone"},
			{name:"Ping_result",type:"simple_textareasingle",rows:'6',mode:"7"}
		]}
	],
	"MDD_Tracert":[
		{type:0,name:"Tracert_info",mode:"no_val",tags:[
			{name:"Tracert_interface_select",type:"simple_select"},
			{name:"Tracert_ip_version_select",type:"simple_select",value:"['ipv4','ipv6']"},
			{name:"Tracert_host_text",type:"simple_text",check:"text_ipDomain"},
			{name:"Tracert_repetition_Number_text",type:"simple_text",check:"text_num",mode:"4",action:"Tracert_start"},
			{name:"Tracert_result_label",type:"info_contextone"},
			{name:"Tracert_result",type:"simple_textareasingle",rows:'6',mode:"8"}
		]}
	],
	"MDD_Inform":[
		{type:0,name:"Inform_info",mode:"no_val",tags:[
			{name:"Title_manual_inform_tips_label",type:"info_contextone"},
			{name:"Inform_button",type:"btn_array",mode:"['Informbtn']",action:"['Inform_save']"},
			//{name:"informStatu0",type:"info_contextone"},
			//{name:"informStatu1",type:"info_contextone"}
			{name:"informStatu",type:"simple_contextwhite"}
		]}
	],
	/*"DD_Ping":[
		{type:0,name:"Ping_info",mode:"no_val",tags:[
			{name:"Ping_interface_select",type:"simple_select"},
			{name:"Ping_ip_version_select",type:"simple_select",value:"['ipv4','ipv6']"},
			{name:"Ping_host_text",type:"simple_text",check:"text_ipDomain"},
			{name:"Ping_repetition_Number_text",type:"simple_text",check:"text_num",mode:"4",action:"ping_start"},
			{name:"Ping_result_label",type:"info_contextone"},
			{name:"Ping_result",type:"simple_textareasingle",rows:'6',mode:"7"}
		]}
	],
	"DD_Tracert":[
		{type:0,name:"Tracert_info",mode:"no_val",tags:[
			{name:"Tracert_interface_select",type:"simple_select"},
			{name:"Tracert_ip_version_select",type:"simple_select",value:"['ipv4','ipv6']"},
			{name:"Tracert_host_text",type:"simple_text",check:"text_ipDomain"},
			{name:"Tracert_repetition_Number_text",type:"simple_text",check:"text_num",mode:"4",action:"Tracert_start"},
			{name:"Tracert_result_label",type:"info_contextone"},
			{name:"Tracert_result",type:"simple_textareasingle",rows:'6',mode:"8"}
		]}
	],
	"DD_Inform":[
		{type:0,name:"Inform_info",mode:"no_val",tags:[
			{name:"Title_manual_inform_tips_label",type:"info_contextone"},
			{name:"Inform_button",type:"btn_array",mode:"['Informbtn']",action:"['Inform_save']"},
			//{name:"informStatu0",type:"info_contextone"},
			//{name:"informStatu1",type:"info_contextone"}
			{name:"informStatu",type:"simple_contextwhite"}
		]}
	],
	"DB_diagnose":[
	  {type:0,name:"linediagnose_info",mode:"val",tags:[
			{name:"linediagnose_list",type:"simple_tabletwo",mode:"2"},
			{name:"linediagnose_button",type:"btn_array",mode:"['linediagnose']",action:"['linediagnose_save']"}		 
		]},
		{type:0,name:"Simulation_info",mode:"no_val",tags:[
			{name:"Simulationnum_text",type:"simple_text"},
			{name:"Simulation_result",type:"simple_context"},
			{name:"Simulation_button",type:"btn_array",mode:"['Simulationbtn']",action:"['Simulation_save']"}
		]}
	],
	"DB_predictive":[
		{type:0,name:"dia_predic_info",mode:"no_val",tags:[
			{name:"Title_db_predictive_label",type:"info_contextone"},
			{name:"predictive_button",type:"btn_array",mode:"['predictivebtn']",action:"['predictivebtn_save']"}
		]}
	],*/
	"HH_Help":[
		{type:0,name:"service_info",mode:"no_val",tags:[
			{name:"Statushelp",type:"info_contextone"},
			{name:"Device_basics",type:"info_contextone"},
			{name:"Information_network_side",type:"info_contextone"},
      {name:"SystemUserInfo",type:"info_contextone"},
      {name:"VoiceInfo",type:"info_contextone"},
      {name:"Service_status",type:"info_contextone"},
      {name:"phonenumber",type:"info_contextone"},
      {name:"mutualcreate",type:"info_contextone"},
      {name:"servicesendstate",type:"info_contextone"},
      {name:"Networkhelp",type:"info_contextone"},
      {name:"Networkmode",type:"info_contextone"},
      {name:"ServiceMode",type:"info_contextone"},
      {name:"BindingSet",type:"info_contextone"},
      {name:"UserNetworkhelp",type:"info_contextone"},
      {name:"start_ip",type:"info_contextone"},
      {name:"end_ip",type:"info_contextone"},
      {name:"Leasetime",type:"info_contextone"},
      {name:"IPaddr",type:"info_contextone"},
      {name:"DHCPClients",type:"info_contextone"},
      {name:"Openwireless",type:"info_contextone"},
      {name:"SSIDhelp",type:"info_contextone"},
      {name:"Areahelp",type:"info_contextone"},
      {name:"RemoteManagementParameters",type:"info_contextone"},
      {name:"Certification",type:"info_contextone"},
      {name:"cer_lead",type:"info_contextone"},
      {name:"QOShelp",type:"info_contextone"},
      {name:"AutomaticallySNtimeserver",type:"info_contextone"},
      {name:"Routes",type:"info_contextone"},
      {name:"Purposehelp",type:"info_contextone"},
      {name:"maskhelp",type:"info_contextone"},
      {name:"Gatewayhelp",type:"info_contextone"},
      {name:"NetInterface",type:"info_contextone"},
      {name:"safehelp",type:"info_contextone"},
      {name:"UrlFilterhelp",type:"info_contextone"},
      {name:"FirewallSecure",type:"info_contextone"},
      {name:"macFilterhelp",type:"info_contextone"},
      {name:"Applicationshelp",type:"info_contextone"},
      {name:"DDNShelp",type:"info_contextone"},//
      {name:"EnableDDNS",type:"info_contextone"},
      {name:"wannamehelp",type:"info_contextone"},
      {name:"ISPhelp",type:"info_contextone"},
      {name:"Servicehostname",type:"info_contextone"},
      {name:"serverporthelp",type:"info_contextone"},
      {name:"DomainName",type:"info_contextone"},
      {name:"usernamehelp",type:"info_contextone"},
      {name:"passwordhelp",type:"info_contextone"},
      {name:"ALGConfiguration",type:"info_contextone"},
      {name:"DMZhelp",type:"info_contextone"},
      {name:"wannamehelp",type:"info_contextone"},
      {name:"HostAddress",type:"info_contextone"},
      {name:"VirtualHostConfiguration",type:"info_contextone"},
      {name:"protohelp",type:"info_contextone"},
      {name:"Internalhosts",type:"info_contextone"},
      {name:"Externalstart_endport",type:"info_contextone"},
      {name:"Internalstart_endport",type:"info_contextone"},
      {name:"upnphelp",type:"info_contextone"},
      {name:"Outboundserveraddress",type:"info_contextone"},
      {name:"Outboundserverport",type:"info_contextone"},
      {name:"AlternateOutserveraddress",type:"info_contextone"},
      {name:"AlternateOutserverport",type:"info_contextone"},
      {name:"Primaryserveraddress",type:"info_contextone"},
      {name:"Mainportnumber",type:"info_contextone"},
      {name:"Alternateserveraddress",type:"info_contextone"},
      {name:"Alternateportnumber",type:"info_contextone"},
      {name:"Local_port",type:"info_contextone"},
      {name:"digitmaphelp",type:"info_contextone"},
      {name:"NumberGraphmatchingmode",type:"info_contextone"},
      {name:"Countriesregions",type:"info_contextone"},
      {name:"Signalingport",type:"info_contextone"},
      {name:"MediaPort",type:"info_contextone"},
      {name:"IGMPApp",type:"info_contextone"},
      {name:"remotedownloading",type:"info_contextone"},
      {name:"managementhelp",type:"info_contextone"},
      {name:"usermanagehelp",type:"info_contextone"},//
      {name:"reboothelp",type:"info_contextone"},
      {name:"USBdeviceconfiguration",type:"info_contextone"},
      {name:"Restorehelp",type:"info_contextone"},
      {name:"Restorefactoryhelp",type:"info_contextone"},
      {name:"Savelog",type:"info_contextone"},
      {name:"loglevel",type:"info_contextone"},
      {name:"logshow",type:"info_contextone"},
      {name:"MaintenanceEnd",type:"info_contextone"},
      {name:"Diagnostichelp",type:"info_contextone"},
      {name:"diapinghelp",type:"info_contextone"},
      {name:"diatracerthelp",type:"info_contextone"},
      {name:"diainformhelp",type:"info_contextone"},
      {name:"VoiceDiagnosishelp",type:"info_contextone"}
		]}
	]
};
